name: AWS Power On
on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start AWS VMs
        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_INSTANCE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      
      - name: Wait For AWS 
        run: |
          sleep 30
